### ISSUE TITLE
Multiple inputs with auto-complete

### ISSUE THREAD

**Issue by eirikant** [ng2-ui/ng2-map#91]
I'm having a hard time figuring out how to add to instances of the autocomplete to the same component. Maybe it's my inexperience, but I can't seem to differentiate the two inputs, and the autocomplete will always just initiate on the last input.

Link to plunker:
https://plnkr.co/edit/QdEfXb02PPClgwY7IoBD

**Comment by allenhwkim** [comment]
It seems like a bug to me at this moment. I will investigate and find a solution;

**Comment by allenhwkim** [comment]
Nice catch @eirikant 
According to this code, https://github.com/ng2-ui/ng2-map/blob/master/src/directives/places-auto-complete.ts#L50

When Google Maps API is not loaded, it loads Google Maps API first, then initialize the autocomplete.

The problem is that, it does not initialize ALL autocomplete, but only the last one registered because there is only one callback can be called by Google.

I need to find a solution for multiple autocomplete inputs when Google API is not loaded.

Meanwhile, you can pre-load Google maps API with `<script>` tag in index.html

**Comment by allenhwkim** [comment]
Duplicate to #92
