### ISSUE TITLE
How to access google's geometry library?

### ISSUE THREAD

**Issue by g-schmitz** [ng2-ui/ng2-map#97]
For calculating the distance of a Polyline I need to have access to the google.maps.geometry library.
Since it isn't available through the maps object itself, how is it possible to access those "external" libraries?

btw I did include the libraries param in the .forRoot({apiUrl:'...'}) method.

For further information take a look at: https://developers.google.com/maps/documentation/javascript/geometry

**Comment by allenhwkim** [comment]
Once you included the library in your forRoot, the library available when the map is initialized.
However, the type of google.maps won't be available on your app component.

You also need to import type to avoid typing errors.

```
function update() {
  var path = [marker1.getPosition(), marker2.getPosition()];
  poly.setPath(path);
  geodesicPoly.setPath(path);
  var heading = google.maps.geometry.spherical.computeHeading(path[0], path[1]);
  document.getElementById('heading').value = heading;
  document.getElementById('origin').value = path[0].toString();
  document.getElementById('destination').value = path[1].toString();
}
```

Since I don't know what errors you are having and how much you tried because there is no example or code provided.

Please follow issue template for faster issue resolving.

**Comment by g-schmitz** [comment]
thank you @allenhwkim, adding the googlemaps typings to my tsconfig.json solved the issue!
