### ISSUE TITLE
More sophisticated control over map directives?

### ISSUE THREAD

**Issue by g-schmitz** [ng2-ui/ng2-map#98]
Is there any demand for adding more control over some of the map directives?

I am particularly thinking about extending `<marker>` and `<custom-marker>` for allowing distinct configurations based on the map's current zoomLevel. So it would be possible to change the icon/icon-size or even showing and hiding the marker at all at different levels.

Any other suggestions? pls let me know because I'm working on this right now.

**Comment by allenhwkim** [comment]
No, there is no demand to extend `marker` and `custom-marker` at this moment.

Regarding to `marker`, we do not accept any behaviour which is not provided by Google because this modules STRICTLY follow Google Maps API V3. We do not invent wheels here.

`custom-marker` is an exception because Google does not have this feature.

Please explain what you want to do in detail to avoid PR getting not accepted in cause your direction and our direction are very different.
